################################################################################
# Environment script generated by ilcsoft-install on Tue Oct  9 18:29:50 2012
# for PandoraPFANew located at [ /afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/PandoraPFANew/v00-09 ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j4"
export CXX="g++"
export ILCSOFT_CMAKE="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/root/5.28.00f"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/lcio/v02-03-01"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/CLHEP/2.1.1.0"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/Marlin/v01-04"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/MarlinReco/v01-05/lib/libMarlinReco.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/PandoraAnalysis/v00-04/lib/libPandoraAnalysis.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/MarlinPandora/v00-09-02/lib/libMarlinPandora.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/LCFIVertex/v00-06-01/lib/libLCFIVertex.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/CEDViewer/v01-06-01/lib/libCEDViewer.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/Overlay/v00-13/lib/libOverlay.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/FastJetClustering/v00-02/lib/libFastJetClustering.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/MarlinFastJet/v00-01/lib/libMarlinFastJet.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/LCTuple/v01-01/lib/libLCTuple.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/MarlinKinfit/v00-01-02/lib/libMarlinKinfit.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/MarlinTrkProcessors/v01-09/lib/libMarlinTrkProcessors.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/Clupatra/v00-09-01/lib/libClupatra.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/LCFIPlus/v00-05-02/lib/libLCFIPlus.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/ForwardTracking/v01-07/lib/libForwardTracking.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/MarlinTPC/v00-10/lib/libMarlinTPC.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/Garlic/v2.10.1/lib/libGarlic.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/lccd/v01-02"


#--------------------------------------------------------------------------------
#     CondDBMySQL
#--------------------------------------------------------------------------------
export COND_DB_DEBUGLOG="/dev/stdout"
export CondDBMySQL="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/CondDBMySQL/CondDBMySQL_ILC-0-9-5"
export LD_LIBRARY_PATH="$CondDBMySQL/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/RAIDA/v01-06-02"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/gear/v01-02-02"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/CMake/2.8.5/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/afs/desy.de/project/ilcsoft/sw/x86_64_gcc41_sl5/v01-16/ilcutil/v01-00"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
